#!/bin/sh
#This script takes links from one of the variables and makes a playlist in mpv. It uses dmenu for variable selection.

Classical=()

Yugo=()

Foreign=()

Games_and_TV=()

choices="Classical\nYugoslav\nForeign\nGames_and_TV"

chosen=$(echo -e "$choices" | dmenu -i)

case $chosen in
	Yugoslav) mpv --shuffle --speed=1.0 $Yugo ;;
	Classical) mpv --shuffle --speed=1.0 $Classical ;;
	Foreign) mpv --shuffle --speed=1.0 $Foreign ;;
	Games_and_TV) mpv --shuffle --speed=1.0 $Games_and_TV ;;
esac
