#!bin/sh
cd /home/nikola/dotfiles/Music

link=$(echo | dmenu -p "Link:" -i)

choices="Classical\nYugo\nForeign\nGames_and_TV"

chosen=$(echo -e "$choices" | dmenu -i)

case $chosen in
	Classical) echo $link >> Classical ;;
	Yugo) echo $link >> Yugo ;;
	Foreign) echo $link >> Foreign ;;
	Games_and_TV) echo $link >> Games_and_TV ;;
esac
